use_frameworks!

platform :ios, '8.0'

target 'TestAddKit_Example' do
  pod 'TestAddKit', :path => '../'

  target 'TestAddKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
